version: '3'
services:
  postgres:
    image: "postgres:9.5.16-alpine"
    ports:
      - "5432:5432"
    container_name: "softplan_db"
    environment:
      - POSTGRES_DB=softplanDB
      - POSTGRES_USER=softplan
      - POSTGRES_PASSWORD=softplan
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
