export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_BY_ID_USER = 'FETCH_BY_ID_USER';
export const CLEAR_SELECTED_USERS = 'CLEAR_SELECTED_USERS';

export const DELETE_USERS = 'DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';

export const SAVE_USERS = 'SAVE_USERS';
export const SAVE_USERS_SUCCESS = 'SAVE_USERS_SUCCESS';

export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';

export const RESET_USER_STORE = 'RESET_USER_STORE';