export const FETCH_PROCESSES = 'FETCH_PROCESSES';
export const FETCH_PROCESSES_SUCCESS = 'FETCH_PROCESSES_SUCCESS';

export const FETCH_BY_ID_PROCESSES = 'FETCH_BY_ID_PROCESSES';
export const FETCH_BY_ID_PROCESSES_SUCCESS = 'FETCH_BY_ID_PROCESSES_SUCCESS';
export const CLEAR_SELECTED_PROCESSES = 'CLEAR_SELECTED_PROCESSES';

export const DELETE_PROCESSES = 'DELETE_PROCESSES';
export const DELETE_PROCESSES_SUCCESS = 'DELETE_PROCESSES_SUCCESS';

export const SAVE_PROCESSES = 'SAVE_PROCESSES';
export const SAVE_PROCESSES_SUCCESS = 'SAVE_PROCESSES_SUCCESS';

export const UPDATE_PROCESSES = 'UPDATE_PROCESSES';
export const UPDATE_PROCESSES_SUCCESS = 'UPDATE_PROCESSES_SUCCESS';

export const RESET_PROCESS_STORE = 'RESET_PROCESS_STORE';