export const FETCH_AUTH = 'FETCH_AUTH';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FAILED  = 'FETCH_AUTH_FAILED';

export const AUTH_RESET_STORE = 'AUTH_RESET_STORE';